config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :restaurants, except: [:edit, :delete, :update] do
    resources :comments
    collection do
      get :summary
    end
    member do
     post 'will_split', to: 'restaurants#will_split'
     post 'wont_split', to: 'restaurants#wont_split'
     post 'tag', to: 'restaurants#tag'
    end
  end

  root to: 'restaurants#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :restaurant
  belongs_to :user

  validates :name, :content, presence: true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  acts_as_votable
  acts_as_taggable
  validates :name, :address, :state, presence: true
  validates :name, uniqueness: {
    scope: [:address, :state],
    message: " this restaurant has already been added."
  }
  validates :state, format: {
    with: /\A([A-Z]{2,2})\z/,
    message: "State must be in two letter format."
  }

  def self.search(search_name, search_location)
    if !search_name.blank? && !search_location.blank?
      where("name LIKE ? AND address LIKE ? OR state LIKE ?", "%#{search_name}%", "%#{search_location}%", "%#{search_location}%")
    elsif search_name.blank?
      where("address LIKE ? OR state LIKE ?", "%#{search_location}%", "%#{search_location}%")
    elsif search_location.blank?
      where("name LIKE ?", "%#{search_name}%")
    else
      return scoped
    end
  end  
end 

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :restaurants
  has_many :comments, dependent: :destroy
  acts_as_voter
  acts_as_taggable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @comment = @restaurant.comments.create(params[:comment].permit(:name, :content).merge({ :name => current_user.email}))
    redirect_to restaurant_path(@restaurant)
  end

  def destroy
    @restaurant = Restaurant.find(params[:restaurant_id])
    @comment = @restaurant.comments.find(params[:id])
    @comment.destroy
    redirect_to restaurant_path(@restaurant)
  end

end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]

  # GET /restaurants
  # GET /restaurants.json
  def index
    @restaurants = Restaurant.all.order('name ASC')
    if params[:name] || params[:location]
      @restaurants = Restaurant.search(params[:name], params[:location]).order('name ASC')
        if @restaurants.blank?
          redirect_to restaurants_path, flash: {notice: "No match."}
        end
    else
      @restaurants = Restaurant.all.order('name ASC')
    end
  end

  # GET /restaurants/1
  # GET /restaurants/1.json
  def show
    @comments = Comment.where(restaurant_id: @restaurant).order("created_at DESC")
  end

  # GET /restaurants/new
  def new
    @restaurant = current_user.restaurants.build
  end

  # GET /restaurants/1/edit
#  def edit
#  end

  # POST /restaurants
  # POST /restaurants.json
  def create
    @restaurant = current_user.restaurants.build(restaurant_params)
    @restaurant.will_split = 0
    @restaurant.wont_split = 0
    @restaurant.tag_list = @restaurant.name

    respond_to do |format|
      if @restaurant.save
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully created.' }
        format.json { render :show, status: :created, location: @restaurant }
      else
        format.html { render :new }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /restaurants/1
  # PATCH/PUT /restaurants/1.json
#  def update
#    respond_to do |format|
#      if @restaurant.update(restaurant_params)
#        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully updated.' }
#        format.json { render :show, status: :ok, location: @restaurant }
#      else
#        format.html { render :edit }
#        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
#      end
#    end
#  end

  # DELETE /restaurants/1
  # DELETE /restaurants/1.json
#  def destroy
#    @restaurant.destroy
#    respond_to do |format|
#      format.html { redirect_to restaurants_url, notice: 'Restaurant was successfully destroyed.' }
#      format.json { head :no_content }
#    end
#  end

  def will_split
    @restaurant = Restaurant.find(params[:id])
    @restaurant.vote_by :voter => current_user, :vote => 'like', :duplicate => true
    redirect_to restaurants_path, flash: {notice: "Will Split vote added!"}
  end

  def wont_split
    @restaurant = Restaurant.find(params[:id])
    @restaurant.vote_by :voter => current_user, :vote => 'bad', :duplicate => true
    redirect_to restaurants_path, flash: {notice: "Won't Split vote added!"}
  end 

  def tag
    @restaurant = Restaurant.find(params[:id])
    if current_user.tag_list.include?(@restaurant.name)
      current_user.tag_list.delete(@restaurant.name)
      current_user.save
    else
      current_user.tag_list += @restaurant.name
      current_user.save
    end
    redirect_to restaurants_path
  end

  def summary
    @user = current_user.email
    @comments = Comment.joins(:restaurant).where(:comments => { :name => @user })
    @restaurants = Restaurant.all.order('name ASC')
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_restaurant
      @restaurant = Restaurant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def restaurant_params
      params.require(:restaurant).permit(:name, :address, :state, :will_split, :wont_split, :tag_list)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/comments/_comment.html.erb
<%= render 'comments/form' %>
  <% @comments.each do |c| %>
    <b><p><%= c.name %></b> | <%= time_ago_in_words(c.created_at) %> ago</p>
      <p><%= c.content %></p>
  <% end %>

app/views/comments/_form.html.erb
<% if current_user != nil %>
  <%= form_for([@restaurant, @restaurant.comments.build]) do |f| %>
    <p>
      <%= f.text_area :content %>
      <%= f.hidden_field :name, :value => current_user.email %>
    </p>
    <p>
      <%= f.submit %>
    </p>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Split The Check?!?</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <div id="header">
    <br>
    <h1 class="title">Split The Check!?!</h1>
    <h2 class="title">Vote if your restaurants will split the check for you</h2>
  </div>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= form_for(restaurant) do |f| %>
  <% if restaurant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(restaurant.errors.count, "error") %> prohibited this restaurant from being saved:</h2>

      <ul>
      <% restaurant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :address %>
    <%= f.text_field :address %>
  </div>

  <div class="field">
    <%= f.label :state %>
    <%= f.text_field :state %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/restaurants/edit.html.erb
<h1>Editing Restaurant</h1>

<%= render 'form', restaurant: @restaurant %>

<%= link_to 'Show', @restaurant %> |
<%= link_to 'Back', restaurants_path %>

app/views/restaurants/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Split The Check?</h1>

<%= form_tag(restaurants_path, :method => "get", id: "search-form") do %>
  <%= text_field_tag :name, params[:name], placeholder: "Search By Name" %>
  <%= text_field_tag :location, params[:location], placeholder: "Search By Location" %>
  <%= submit_tag "Search", name: nil %>
<% end %>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>State</th>
      <th>Will Split</th>
      <th>Won't Split</th>
      <% if user_signed_in? %>
        <th>Favorite</th>
      <% end %>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @restaurants.each do |restaurant| %>
      <tr class="<%= cycle('list_line_odd', 'list_line_even') %>">
        <td><%= restaurant.name %></td>
        <td><%= restaurant.address %></td>
        <td><%= restaurant.state %></td>
	<% if user_signed_in? %>
        <td class="button"><%= button_to restaurant.get_upvotes.size, will_split_restaurant_path(restaurant), method: :post %></td>
        <td class="button"><%= button_to restaurant.get_downvotes.size, wont_split_restaurant_path(restaurant), method: :post %></td>
	<% else %>
	<td><%= restaurant.get_upvotes.size %></td>
	<td><%= restaurant.get_downvotes.size %></td>
        <% end %>
        <% if user_signed_in? %>
          <% if current_user.tag_list.include?(restaurant.name) %>
            <td class="button"><%= button_to "Unfavorite", tag_restaurant_path(restaurant), method: :post %></td>
          <% else %>
            <td class="button"><%= button_to "Favorite", tag_restaurant_path(restaurant), method: :post %></td>
	  <% end %>
        <% end %>
        <td><%= link_to "View", restaurant_path(restaurant) %></td>

      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if user_signed_in? %>
  <%= link_to 'New Restaurant', new_restaurant_path %>
<% end %>
<%= link_to 'Back', restaurants_path %>

<br><br><br>

<% if user_signed_in? %>
  <%= link_to "Logout", destroy_user_session_path, :method => :delete %>
  <%= link_to "History", summary_restaurants_path %>
<% else %>
  <%= link_to "Sing Up", new_user_registration_path %>
  <%= link_to "Sign In", new_user_session_path %>
<% end %>

app/views/restaurants/new.html.erb
<h1>New Restaurant</h1>

<%= render 'form', restaurant: @restaurant %>

<%= link_to 'Back', restaurants_path %>

app/views/restaurants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @restaurant.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @restaurant.address %>
</p>

<p>
  <strong>State:</strong>
  <%= @restaurant.state %>
</p>

<p>
  <strong>Will split:</strong>
  <%= @restaurant.will_split %>
</p>

<p>
  <strong>Wont split:</strong>
  <%= @restaurant.wont_split %>
</p>

<%= render 'comments/comment' %>

<%= link_to 'Back', restaurants_path %>

app/views/restaurants/summary.html.erb
<p><strong>Summary For: </strong><%= @user %></p>

<p><strong>User Comments:</strong></p>
  <table>
    <thead>
      <tr>
        <th>Restaurant</th>
        <th>Comment</th>
        <th>Time</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @comments.each do |c| %>
        <tr>
          <td><b><%= link_to c.restaurant.name, restaurant_path(c.restaurant) %></b></td>
          <td><%= c.content %></td>
          <td><%= time_ago_in_words(c.created_at) %> ago</td>
        </tr>
      <% end %>
    </tbody>
  </table>

<p><strong>User Votes:</strong></p>
  <table>
    <thead>
      <tr>
        <th>Restaurant</th>
        <th>Will Split</th>
        <th>Won't Split</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% @restaurants.each do |r| %>
        <% if r.votes_for.voters.include?(current_user) %>
          <tr>
            <td><b><%= link_to r.name, restaurant_path(r) %></b></td>
            <td><%= r.votes_for.up.size %></td>
            <td><%= r.votes_for.down.size %></td>
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>

<p><strong>User Favorites:</strong></p>
  <table>
    <thead>
      <tr>
        <th>Restaurant</th>
        <th>Location</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% @restaurants.each do |r| %>
        <% if current_user.tag_list.include?(r.name) %>
          <tr>
            <td><% r.name %></td>
            <td><% r.address %></td>
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>


<% if user_signed_in? %>
  <%= link_to 'New Restaurant', new_restaurant_path %>
<% end %>
<%= link_to 'Back', restaurants_path %>

<br><br><br>

<% if user_signed_in? %>
  <%= link_to "Logout", destroy_user_session_path, :method => :delete %>

<% else %>
  <%= link_to "Sing Up", new_user_registration_path %>
  <%= link_to "Sign In", new_user_session_path %>
<% end %>